name: Cypress Tests

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  cypresstests:
    runs-on: ubuntu-latest
    container:
      image: cypress/included:14.5.4
      env:
        BASE_URL: http://localhost:2221/
        ADMIN_USERNAME: ${{ secrets.ADMIN_USERNAME }}
        ADMIN_PASSWORD: ${{ secrets.ADMIN_PASSWORD }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Start the shopping store application
        run: |
          echo "Start the shopping store application"
          chmod +x ./shopping-store/shopping-store-linux-amd64 && ./shopping-store/shopping-store-linux-amd64 &

          echo "Install dependencies from lockfile"
          npm ci

          echo "Run Cypress tests"
          npm run test:ci
